#include "type.h"
#include "config.h"
#include "stdio.h"
#include "const.h"
#include "string.h"
#include "protect.h"
#include "fs.h"
#include "tty.h"
#include "console.h"
#include "proc.h"
#include "global.h"//golobal.h 中此时EXTERN = null，即此处为定义
#include "proto.h"